global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'onedev'
    static_configs:
      - targets: ['172.20.10.4:6610']  

  - job_name: 'exporter'
    static_configs:
      - targets: ['exporter:9101']
